"""Task 1 — Schwab allocator ingestion adapter, end to end through assess().

Loads a committed REAL fixture (27 allocator config variants over 2005-2026,
monthly net returns, generated by examples/gen_schwab_trials.py from the Schwab
allocator backtest) and asserts the verdict is well-formed. It does NOT assert a
particular band — CRUCIBLE's job is to report whatever the data says, not a
flattering target.
"""
from __future__ import annotations

from pathlib import Path

import numpy as np

from crucible.ingest import load_schwab
from crucible.verdict import assess

FIXTURE = Path(__file__).parent / "fixtures" / "schwab_export.csv"


def test_load_schwab_shapes_are_clean():
    M, chosen = load_schwab(str(FIXTURE))
    assert M.ndim == 2 and M.shape[1] >= 2          # a real trial matrix
    assert chosen.ndim == 1 and chosen.shape[0] == M.shape[0]
    assert np.isfinite(M).all() and np.isfinite(chosen).all()


def test_assess_on_real_schwab_export_is_wellformed():
    M, chosen = load_schwab(str(FIXTURE))
    v = assess(chosen, n_trials=M.shape[1], trials_matrix=M, pbo_groups=10)

    assert v.band in {"green", "yellow", "red"}                  # valid band
    assert 0.0 <= v.deflation.deflated_sharpe <= 1.0             # DSR is a probability
    assert v.deflation.n_trials == M.shape[1]                    # multiple-testing count wired
    assert v.pbo is not None                                     # N >= 2 -> PBO present
    assert 0.0 <= v.pbo.pbo <= 1.0
    assert 0.0 <= v.deflation.psr_vs_zero <= 1.0
